name: Build and Push Test Model Trainer Image

env:
  VERSION: "v0.0.2"
  MODEL_NAME: "customer-churn"

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ml/test-model-trainer/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Github env
        run: |
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MODEL_NAME=$MODEL_NAME" >> $GITHUB_ENV

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ml/test-model-trainer/
          file: ml/test-model-trainer/Dockerfile
          push: false
          tags:  ${{ github.sha }}

      - name: Configure shared services AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{vars.AWS_ACCOUNT_ID_DATA_INTEGRATION_DEV}}:role/github/repository/${{ github.event.repository.name }}-github-actions
          role-session-name: GitHubActions
          aws-region: eu-west-1
          special-characters-workaround: true

      - name: Login to Amazon ECR shared-services
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Push Docker Image to AWS ECR shared services
        run: |
          ecr_repo_url="${{ vars.AWS_ACCOUNT_ID_DATA_INTEGRATION_DEV }}.dkr.ecr.eu-west-1.amazonaws.com/pleo/ml/training/${{ env.MODEL_NAME }}:${{ env.VERSION }}"
          docker tag ${{ github.sha }} ${ecr_repo_url}
          docker push ${ecr_repo_url}
          docker rmi -f ${ecr_repo_url}